# Generated by Django 6.0.2 on 2026-03-15 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admissionenquiry',
            table='mydata',
        ),
    ]
