# Generated by Django 6.0.2 on 2026-03-15 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_admissionenquiry_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admissionenquiry',
            table=None,
        ),
    ]
