# Generated by Django 6.0.2 on 2026-03-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_admissionenquiry_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionenquiry',
            name='phone',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
