# Generated by Django 6.0.2 on 2026-03-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_admissionenquiry_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionenquiry',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted')], default='New', max_length=20),
        ),
    ]
